In [ ]:
import pandas as pd

df1 = pd.read_csv('new各鄉鎮市區人口密度.csv')
df1

In [ ]:
import pandas as pd

df1 = pd.read_csv('new各鄉鎮市區人口密度.csv')
display(df1)
type(df1.style)

In [ ]:
import pandas as pd

df1 = pd.read_csv('new各鄉鎮市區人口密度.csv')
display(df1)
def format1(value:int):
    return f"第{value}號"
df1.style\
.format(precision=2,thousands=',',decimal='.')\
.format_index(format1)

In [ ]:
df1 = pd.read_csv('new各鄉鎮市區人口密度.csv')
display(df1)
df1.style\
.format(precision=2,thousands=',',decimal='.')\
.format_index(lambda value:f'第{value}號')

In [5]:
import numpy as np
weather_df = pd.DataFrame(np.random.rand(10,2)*5,
                        index=pd.date_range(start="2021-01-01", periods=10),
                        columns=["Tokyo", "Taipei"])

In [6]:
weather_df.style\
.set_caption('Weather Conditions')\
.format_index(lambda v:v.strftime("%A"))

In [7]:
weather_df.style\
.set_caption('Weather Conditions')\
.format_index(lambda v:v.strftime("%a"))\
.background_gradient(vmin=1,vmax=5)

In [8]:
weather_df.index

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10'],
              dtype='datetime64[ns]', freq='D')